config:
  framework: "hardhat" 
  framework_version: "^2.17.3" 
  node_version: "20" 
  package_manager: "yarn"

environment:
  SNOWTRACE_API_KEY: "86BB07a534ADF43786ECA5Dd34A97e3F96927e4F"
  ARBISCAN_API_KEY: "86BB07a534ADF43786ECA5Dd34A97e3F96927e4F"
  PRIVATE_KEY_DEPLOYER: "86BB07a534ADF43786ECA5Dd34A97e3F96927e4F"
  REPORT_GAS: false

tasks:
  install-dependencies:
    - yarn install