config:
  framework: "foundry" 
  package_manager: "forge"

environment:
  "SNOWTRACE_API_KEY": "a3f1b2c4d5e6f7890a1b2c3d4e5f6789a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5"
  "ARBISCAN_API_KEY": "8a3f1b2c4d5e6f7890a1b2c3d4e5f6789a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5"
  "PRIVATE_KEY_DEPLOYER": "a3f1b2c4d5e6f7890a1b2c3d4e5f6789a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5"
  "REPORT_GAS": "false"

tasks:
  install-dependencies:
    - forge install
    - npm install --global yarn
    - yarn install